sonar.projectKey=devAndreotti_quality-gate
sonar.organization=devAndreotti

sonar.projectName=quality-gate

sonar.sources=scripts

sonar.tests=scripts
sonar.test.inclusions=**/*.test.cjs

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.cpd.exclusions=**/*.test.cjs

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
